name: Validation Production Pull Request

on:
  pull_request: 
    branches:
      -master
    paths:
      - 'force-app/**'
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - user: actions/checkout@v3
      - name: Validate in Production
        with:
          SFDX_AUTH_URL: ${{ secrets.SFDX_AUTH_URL }}
          DRY_RUN: true
          