name: Validation Production Pull Request

on:
  workflow_dispatch:
  pull_request: 
    branches:
      - main
      - UAT
    paths:
      - 'force-app/**'
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      # Install Salesforce CLI via NPM
      - name: Install Salesforce CLI
        run: |
          npm install -g @salesforce/cli
          sf --version  
          echo "Branch = ${{ github.ref_name }}"
          echo "Event = ${{ github.event_name }}"
          

  validate-to-uat:
    if: github.ref == 'refs/heads/UAT'
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v4
      - name: Validate in UAT
        uses: jawills/sf-deploy@v1.0
        with:
          SFDX_AUTH_URL: ${{ secrets.SFDX_UAT_AUTH_URL }}
          DRY_RUN: true        
            
  validate-to-prod:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v4
      - name: Validate in Production
        uses: jawills/sf-deploy@v1.0
        with:
          SFDX_AUTH_URL: ${{ secrets.SFDX_AUTH_URL }}
          DRY_RUN: true     
