name: Validation Production Pull Request

on:
  workflow_dispatch:
  pull_request: 
    branches:
      - main
    paths:
      - 'force-app/**'
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
     # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      # Install Salesforce CLI via NPM
      - name: Install Salesforce CLI
        run: |
          npm install -g @salesforce/cli
          sf --version    
      - uses: actions/checkout@v4
      - name: Validate in Production
        uses: jawills/sf-deploy@v1.0
        with:
          SFDX_AUTH_URL: ${{ secrets.SFDX_AUTH_URL }}
          DRY_RUN: true
